export type LoanType = 'CD' | 'HP' | 'STBD' | 'TBD' | 'FD' | 'OD' | 'RD';

export interface Loan {
  id?: string; // Optional - generated by database for new loans
  number: number;
  date: string;
  loanType: LoanType;
  customerName: string;
  fatherName?: string;
  aadhaar?: string;
  cNo?: string;
  address: string;
  phone1?: string;
  phone2?: string;
  guarantor1?: {
    name: string;
    aadhaar?: string;
    phone?: string;
  };
  guarantor2?: {
    name: string;
    aadhaar?: string;
    phone?: string;
  };
  particulars?: string;
  loanAmount: number;
  rateOfInterest?: number;
  period: number; // in days
  documentCharges?: number;
  partnerId?: string;
  partnerName?: string;
  userName: string;
  entryTime: string;
  // Image URLs from Supabase Storage
  customerImageUrl?: string;
  guarantor1ImageUrl?: string;
  guarantor2ImageUrl?: string;
  partnerImageUrl?: string;

  // ── Documents submitted with the loan ──────────────────────
  documents?: LoanDocuments;

  // ── Location captured for asset/land/collateral ────────────
  location?: LoanLocation;

  // ── Free-form description + extra features ─────────────────
  description?: string;
  extraFeatures?: string;
}

export interface DocumentItem {
  /** Was this type of document submitted? */
  submitted: boolean;
  /** Name / title of the document. */
  title?: string;
  /** Free-form notes — number, issuing authority, expiry, etc. */
  notes?: string;
}

export interface LoanDocuments {
  /** Financial documents — bank statements, income proof, GST returns, etc. */
  financial: DocumentItem[];
  /** Original documents — land papers, property deeds, asset proofs. */
  original: DocumentItem[];
  /** Registration documents — joint registration with the finance company. */
  registration: DocumentItem[];
}

export interface LoanLocation {
  /** Full address of the asset / pledged property. */
  address?: string;
  /** Pincode. */
  pincode?: string;
  /** Village / Town. */
  village?: string;
  /** Mandal. */
  mandal?: string;
  /** District. */
  district?: string;
  /** State. */
  state?: string;
  /** Exact GPS latitude (float). */
  latitude?: number;
  /** Exact GPS longitude (float). */
  longitude?: number;
  /** Google / Plus-code / shortlink — whatever the admin pastes. */
  mapLink?: string;
  /** Landmark — nearby references. */
  landmark?: string;
}

export interface Transaction {
  id?: string; // Optional - generated by database for new transactions
  date: string;
  accountName: string;
  particulars: string;
  rno?: string;
  number?: string;
  credit: number;
  debit: number;
  userName: string;
  entryTime: string;
  transactionType?: string; // Optional: 'cash_book_entry', 'loan_transaction', 'capital_entry', etc.
}

export interface Partner {
  id: string;
  name: string;
  phone?: string;
  address?: string;
  partnerId?: number;
  isMD?: boolean;
  mdName?: string;
  village?: string;
  homePhone?: string;
}

export interface AccountSummary {
  accountName: string;
  credit: number;
  debit: number;
}

export interface DailyReport {
  date: string;
  transactions: Transaction[];
  accountSummary: AccountSummary[];
  creditTotal: number;
  debitTotal: number;
  openingBalance: number;
  closingBalance: number;
  grandTotal: number;
}

export interface DayBookEntry {
  sn: number;
  headOfAccount: string;
  particulars: string;
  number?: string;
  credit: number;
  debit: number;
}

export interface Installment {
  sn: number;
  dueDate: string;
  installmentAmount: number;
  paidAmount: number;
  dueAmount: number;
  paidDate?: string;
  dueDays: number;
  penalty: number;
}

export interface LedgerTransaction {
  date: string;
  credit: number;
  debit: number;
  particulars?: string;
  rno?: string;
}

export interface CDLoan extends Loan {
  receiptNo?: number;
  rate?: number;
  // Overdue interest rate (e.g. 3.75%) applied on interest after due date
  overdueRate?: number;
  amountPaid?: number;
  presentInterest?: number;
  totalBalance?: number;
  documentStatus?: string;
  documentType?: string;
  loanDate?: string;
  dueDate?: string;
  dueDays?: number;
  nextDueDate?: string;
  penalty?: number;
  totalAmtForRenewal?: number;
  totalAmtForClose?: number;
  documentReturned?: boolean;
}

export interface STBDLoan extends Loan {
  accountNumber?: number;
  instPayingReceiptNo?: number;
  installmentAmount?: number;
  totalInstallments?: number;
  loanDate?: string;
  lastDate?: string;
  dueDate?: string;
  totalAmount?: number;
  lateFees?: number;
  totalPayable?: number;
  installments?: Installment[];
}

export interface TBDLoan extends Loan {
  accountNumber?: number;
  premium?: number;
  premiumDays?: number;
  paidAmount?: number;
  paidDays?: number;
  dueAmount?: number;
  totalDays?: number;
  dueDays?: number;
  joinedDate?: string;
  dueDate?: string;
}

export interface NPALoan {
  id: string;
  date: string;
  number: string;
  name: string;
  npaAmount: number;
  aadhaar?: string;
  phone?: string;
  isNPA: boolean;
  npaDate?: string;
  loanType: LoanType;
  partnerName?: string;
}

export interface BusinessSummary {
  partnerName: string;
  totalLoan: number;
  totalPaid: number;
  balanceWith: number;
  actualLoan: number;
  actualPaid: number;
  balanceWithout: number;
}

export interface LoanSearchResult {
  runningLoans: Loan[];
  asGuarantor1: Loan[];
  asGuarantor2: Loan[];
  allLoans: Loan[];
}

